### ISSUE TITLE
Can we configure timeout for force-resolutions or increase it?

### ISSUE THREAD

**Issue by bilalbaqar** [rogeriochaves/npm-force-resolutions#33]
I seem to be hitting [this](https://github.com/rogeriochaves/npm-force-resolutions/blob/master/src/npm_force_resolutions/core.cljs#L70) timeout while running version 0.0.10. 

```
npx npm-force-resolutions
/home/jenkins/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:61
  (go
  ^
Error: Timeout trying to fetch resolutions from npm
    at switch__2144__auto__ (/home/jenkins/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:61:3)
    at /home/jenkins/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:61:3
    at npm_force_resolutions$core$find_resolutions_$_state_machine__2145__auto____1 (/home/jenkins/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:476:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (/home/jenkins/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:492:85)
    at cljs.core.async.impl.ioc-helpers/run-state-machine (/home/jenkins/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
    at cljs.core.async.impl.ioc-helpers/run-state-machine-wrapped (/home/jenkins/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
    at fret (/home/jenkins/node_modules/npm-force-resolutions/out/cljs/core/async.cljs:490:22)
    at take-cb (/home/jenkins/node_modules/npm-force-resolutions/out/cljs/core/async.cljs:188:63)
    at /home/jenkins/node_modules/npm-force-resolutions/out/cljs/core/async/impl/channels.cljs:160:45
    at Immediate.cljs$core$async$impl$dispatch$process_messages (/home/jenkins/node_modules/npm-force-resolutions/out/cljs/core/async/impl/dispatch.cljs:18:7)
```

Downgraded to 0.0.3 and it worked.

**Comment by anisimov74** [comment]
I'm suffering from this problem. How can I work it around?

**Comment by amitrai4code** [comment]
Downgrading to v 0.0.3 fixed the issue for.
`"preinstall": "npx npm-force-resolutions@0.0.3"`

**Comment by trigunam** [comment]
> Downgrading to v 0.0.3 fixed the issue for. `"preinstall": "npx npm-force-resolutions@0.0.3"`

This actually worked even in CentOS for CICD.

**Comment by runderworld** [comment]
@rogeriochaves  broken since [this commit](https://github.com/rogeriochaves/npm-force-resolutions/commit/b006bb3d2ae2160f5620ef86627d882eeffefb28#diff-5ec13dbefceeb57d7602c1d76dd13efead4c6ec7e6b298f54a6322a691607740R48) for v0.0.4 (Feb 2021); any possibility of increasing timeout or making it configurable?

**Comment by kv0906** [comment]
I'm using Mac os 12 ( chip M1 ) encounter this issue. Can someone help me to workaround?

**Comment by AlbertoMeQ** [comment]
This is still happening. Can we get a configurable timeout or simply a much longer one?

**Comment by gabriel-barros-pontes** [comment]
When I use `"preinstall": "npx npm-force-resolutions@0.0.3"` my npm audit still shows critical vulnerabilities.
Is there a new solution to this problem?
I am using npm-force-resolutions to fix vulnerabilities in my component library.

**Comment by billysandle95** [comment]
This is still a problem for v0.0.10, downgrading to v0.0.3 has temporarily addressed the issue. Is there any update on when a fix may be available in a future version?
